[package]
name = "cconst"
description = "Create compile-time evaluated constants of Copy-trait implementing types"
version = "0.2.2"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
license = "MIT"
docs = "https://docs.rs/cconst"
repository = "https://github.com/mbr/cconst"

[dependencies]
